name: Deploy Laravel App to DigitalOcean

on:
  push:
    branches:
      - staging
      - main

jobs:
  scan-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh-add ./ssh_key
          ssh-keyscan 138.68.74.116 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Code Scanning
        run: |
          cd /var/www/taxsearch-be
          composer install
          php artisan key:generate
          phpstan analyze
          phpcs --standard=PSR2 app

      - name: Deploy
        run: |
          ssh root@138.68.74.116 "cd /var/www/taxsearch-be && git pull origin $GITHUB_REF && composer install && php artisan migrate && php artisan config:cache && php artisan route:cache && php artisan optimize && php artisan key:generate"
        env:
          GITHUB_REF: ${{ github.ref }}
